const ifj = @import("ifj24.zig");

pub fn main() void {
    // Test prázdného řetězce
    ifj.write("");

    // Výpis všech validních ASCII znaků bez cyklu
    ifj.write(" ");
    ifj.write("!");
    ifj.write("#");
    ifj.write("$");
    ifj.write("%");
    ifj.write("&");
    ifj.write("'");
    ifj.write("(");
    ifj.write(")");
    ifj.write("*");
    ifj.write("+");
    ifj.write(",");
    ifj.write("-");
    ifj.write(".");
    ifj.write("/");
    ifj.write("0");
    ifj.write("1");
    ifj.write("2");
    ifj.write("3");
    ifj.write("4");
    ifj.write("5");
    ifj.write("6");
    ifj.write("7");
    ifj.write("8");
    ifj.write("9");
    ifj.write(":");
    ifj.write(";");
    ifj.write("<");
    ifj.write("=");
    ifj.write(">");
    ifj.write("?");
    ifj.write("@");
    ifj.write("A");
    ifj.write("B");
    ifj.write("C");
    ifj.write("D");
    ifj.write("E");
    ifj.write("F");
    ifj.write("G");
    ifj.write("H");
    ifj.write("I");
    ifj.write("J");
    ifj.write("K");
    ifj.write("L");
    ifj.write("M");
    ifj.write("N");
    ifj.write("O");
    ifj.write("P");
    ifj.write("Q");
    ifj.write("R");
    ifj.write("S");
    ifj.write("T");
    ifj.write("U");
    ifj.write("V");
    ifj.write("W");
    ifj.write("X");
    ifj.write("Y");
    ifj.write("Z");
    ifj.write("[");
    ifj.write("\\\\");
    ifj.write("]");
    ifj.write("^");
    ifj.write("_");
    ifj.write("`");
    ifj.write("a");
    ifj.write("b");
    ifj.write("c");
    ifj.write("d");
    ifj.write("e");
    ifj.write("f");
    ifj.write("g");
    ifj.write("h");
    ifj.write("i");
    ifj.write("j");
    ifj.write("k");
    ifj.write("l");
    ifj.write("m");
    ifj.write("n");
    ifj.write("o");
    ifj.write("p");
    ifj.write("q");
    ifj.write("r");
    ifj.write("s");
    ifj.write("t");
    ifj.write("u");
    ifj.write("v");
    ifj.write("w");
    ifj.write("x");
    ifj.write("y");
    ifj.write("z");
    ifj.write("{");
    ifj.write("|");
    ifj.write("}");
    ifj.write("~");

    // Speciální escape sekvence
    ifj.write("\n");
    ifj.write("Escape sekvence:");
    ifj.write("\n");
    ifj.write("\\n\n");
    ifj.write("\n");
    ifj.write("\\r\r");
    ifj.write("\n");
    ifj.write("\\t\t");
    ifj.write("\n");
    ifj.write("\\\\");
    ifj.write("\n");
    ifj.write("\\\"");
    ifj.write("\n");

    // Test hexadecimálních escape sekvencí \xdd
    ifj.write("\x20\x21\x22\x23\x24\x25\x26\x27\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x3A\x3B\x3C\x3D\x3E\x3F\x40\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4A\x4B\x4C\x4D\x4E\x4F\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5A\x5B\x5C\x5D\x5E\x5F\x60\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6A\x6B\x6C\x6D\x6E\x6F\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7A\x7B\x7C\x7D\x7E");
}
