#ifndef TERMINALS_H
#define TERMINALS_H

#include <string>
#include <unordered_map>
#include <unordered_set>
#include <stdexcept>
#include "nonterminals.h"


enum Terminal {
    T_CONST,
    T_IFJ,
    T_EQUAL,
    T_AT_IMPORT,
    T_LEFT_PARENTHESIS,
    T_RIGHT_PARENTHESIS,
    T_SEMICOLON,
    T_PUB,
    T_FN,
    T_ID,
    T_COLON,
    T_COMMA,
    T_VOID,
    T_INT,
    T_INT_OR_NULL,
    T_FLOAT,
    T_FLOAT_OR_NULL,
    T_STRING,
    T_STRING_OR_NULL,
    T_VAR,
    T_IF,
    T_ELSE,
    T_PIPE,
    T_LEFT_CURLY_BRACKET,
    T_RIGHT_CURLY_BRACKET,
    T_WHILE,
    T_RETURN,
    T_DOUBLE_EQUAL,
    T_NOT_EQUAL,
    T_LESS_THAN,
    T_GREATER_THAN,
    T_LESS_THAN_OR_EQUAL,
    T_GREATER_THAN_OR_EQUAL,
    T_PLUS,
    T_MINUS,
    T_MULTIPLY,
    T_DIVIDE,
    T_DOT,
    T_INT_LITERAL,
    T_FLOAT_LITERAL,
    T_STRING_LITERAL,
    T_NULL_LITERAL,
    T_EOF,
    TERMINAL_COUNT,  // Number of terminals
    T_EPSILON,
};

std::unordered_map<std::string, Terminal> terminalMap = {
    {"CONST", T_CONST},
    {"IFJ", T_IFJ},
    {"EQUAL", T_EQUAL},
    {"AT_IMPORT", T_AT_IMPORT},
    {"LEFT_PARENTHESIS", T_LEFT_PARENTHESIS},
    {"RIGHT_PARENTHESIS", T_RIGHT_PARENTHESIS},
    {"SEMICOLON", T_SEMICOLON},
    {"PUB", T_PUB},
    {"FN", T_FN},
    {"ID", T_ID},
    {"COLON", T_COLON},
    {"COMMA", T_COMMA},
    {"VOID", T_VOID},
    {"INT", T_INT},
    {"INT_OR_NULL", T_INT_OR_NULL},
    {"FLOAT", T_FLOAT},
    {"FLOAT_OR_NULL", T_FLOAT_OR_NULL},
    {"STRING", T_STRING},
    {"STRING_OR_NULL", T_STRING_OR_NULL},
    {"VAR", T_VAR},
    {"IF", T_IF},
    {"ELSE", T_ELSE},
    {"PIPE", T_PIPE},
    {"LEFT_CURLY_BRACKET", T_LEFT_CURLY_BRACKET},
    {"RIGHT_CURLY_BRACKET", T_RIGHT_CURLY_BRACKET},
    {"WHILE", T_WHILE},
    {"RETURN", T_RETURN},
    {"DOUBLE_EQUAL", T_DOUBLE_EQUAL},
    {"NOT_EQUAL", T_NOT_EQUAL},
    {"LESS_THAN", T_LESS_THAN},
    {"GREATER_THAN", T_GREATER_THAN},
    {"LESS_THAN_OR_EQUAL", T_LESS_THAN_OR_EQUAL},
    {"GREATER_THAN_OR_EQUAL", T_GREATER_THAN_OR_EQUAL},
    {"PLUS", T_PLUS},
    {"MINUS", T_MINUS},
    {"MULTIPLY", T_MULTIPLY},
    {"DIVIDE", T_DIVIDE},
    {"DOT", T_DOT},
    {"INT_LITERAL", T_INT_LITERAL},
    {"FLOAT_LITERAL", T_FLOAT_LITERAL},
    {"STRING_LITERAL", T_STRING_LITERAL},
    {"NULL_LITERAL", T_NULL_LITERAL},
    {"EOF", T_EOF},
    {"EPSILON", T_EPSILON},
};

std::array<std::string, TERMINAL_COUNT> invTerminalMap = {
    "const",
    "ifj",
    "=",
    "@import",
    "(",
    ")",
    ";",
    "pub",
    "fn",
    "id",
    ":",
    "c",
    "void",
    "i32",
    "?i32",
    "f64",
    "?f64",
    "[]u8",
    "?[]u8",
    "var",
    "if",
    "else",
    "|",
    "{",
    "}",
    "while",
    "return",
    "==",
    "!=",
    "<",
    ">",
    "<=",
    ">=",
    "+",
    "-",
    "*",
    "/",
    ".",
    "INT_LITERAL",
    "FLOAT_LITERAL",
    "STRING_LITERAL",
    "NULL_LITERAL",
    "EOF",
};

Terminal getTerminal(const std::string& token) {
    // Ensure the token exists in the map to avoid exceptions
    auto it = terminalMap.find(token);
    if (it != terminalMap.end()) {
        return it->second;
    }
    throw std::invalid_argument("Invalid token"); // Handle the case where the token is not found
}

#endif // TERMINALS_H