/*******************************************************************************
 *                                                                             *
 * Název projektu:   Implementace překladače imperativního jazyka IFJ24        *
 *                                                                             *
 * Soubor:           lltable.c                                                 *
 * Autor:            Jan Kalina   <xkalinj00> (autor LL-gramatiky)             *
 *                   David Krejčí <xkrejcd00> (autor LL-tabulky)               *
 *                                                                             *
 * Datum:            24.10.2024                                                *
 * Poslední změna:   07.11.2024                                                *
 *                                                                             *
 * Tým:      Tým xkalinj00                                                     *
 * Členové:  Farkašovský Lukáš    <xfarkal00>                                  *
 *           Hýža Pavel           <xhyzapa00>                                  *
 *           Kalina Jan           <xkalinj00>                                  *
 *           Krejčí David         <xkrejcd00>                                  *
 *                                                                             *
 ******************************************************************************/
/**
 * @file lltable.c
 * @author Jan Kalina   \<xkalinj00> (autor LL-gramatiky)
 * @author David Krejčí \<xkrejcd00> (autor LL-tabulky)
 *
 * @brief Implementační soubor pro správu LL tabulky.
 * @details Tento implementační soubor obsahuje definice funkcí a datových
 *          struktur potřebných pro správu LL tabulky v překladači.
 *          LL tabulka je používána pro LL syntaktickou analýzu a obsahuje
 *          pravidla pro přechody mezi stavy.
 */

#include "lltable.h"

/* Definice globální proměnné pro mapu terminálů pro LL tabulku.
   Namapování terminálů pro účely hashování v tabulce symbolů na základě klíčů */
const char *terminalMap[TERMINAL_COUNT] = {
    "id",
    "@import",
    "ifj",
    "pub",
    "fn",
    "const",
    "var",
    "if",
    "else",
    "while",
    "return",
    "=",
    "+",
    "-",
    "*",
    "/",
    "==",
    "!=",
    "<",
    ">",
    "<=",
    ">=",
    "i32",
    "?i32",
    "f64",
    "?f64",
    "[]u8",
    "?[]u8",
    "void",
    "INT_LITERAL",
    "FLOAT_LITERAL",
    "STRING_LITERAL",
    "NULL_LITERAL",
    ".",
    ",",
    ":",
    ";",
    "|",
    "(",
    ")",
    "{",
    "}",
    "EOF",
    "EPSILON"
};

/* Definice globální proměnné pro LL tabulku. Každý řádek tabulky obsahuje    */
/* hash klíč a pole hodnot pro neterminály. */
LLtable table[TERMINAL_COUNT] = {
	{T_HASH_FN,                   {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_ID,                   {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  PARAMETERS_1,  PARAM_LIST,    PARAM,         PARAM_LIST_REST_1,  SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_2,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_1,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_IF,                   {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_3,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  IF,            SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_DOT,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_EOF,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  FUN_DEF_LIST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_IFJ,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  STATEMENT_REST_3,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_2,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_INT,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_1,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_PUB,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  FUN_DEF_LIST_1,  FUN_DEF,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_VAR,                  {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_1,   SYNTAX_ERROR,      VAR_DEF,       MODIFIABLE_1,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_ELSE,                 {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_PIPE,                 {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  NULL_COND_1,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_PLUS,                 {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  ADD_EXPR_REST_1,  ADD_OP_1,      SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_VOID,                 {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_2,  SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_COLON,                {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  POSSIBLE_TYPE_1,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_COMMA,                {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  ARG_1,         SYNTAX_ERROR}},
	{T_HASH_CONST,                {PROGRAM,       PROLOGUE,      SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_1,   SYNTAX_ERROR,      VAR_DEF,       MODIFIABLE_2,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_FLOAT,                {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_3,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_MINUS,                {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  ADD_EXPR_REST_1,  ADD_OP_2,      SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_WHILE,                {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_4,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  WHILE,         SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_IMPORT,               {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
    {T_HASH_RETURN,               {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_1,  STATEMENT_5,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN,        SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_STRING,               {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_5,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_EPSILON,              {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_DIVISION,             {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_1,  MULTI_OP_2,    SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
    {T_HASH_IDENTITY,             {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_1,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
    {T_HASH_LESS,                 {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_3,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_NOT_EQUAL,            {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_2,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_SEMICOLON,            {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_FLOAT_LITERAL,        {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_3,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  LITERAL_2}},
	{T_HASH_FLOAT_OR_NULL,        {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_4,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_LEFT_BRACKET,         {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  STATEMENT_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_4,        TERM_REST_1,   ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_ASSIGNMENT,           {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  STATEMENT_REST_1,  SYNTAX_ERROR,  SYNTAX_ERROR,  POSSIBLE_TYPE_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
    {T_HASH_GREATER_OR_EQUAL,     {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_6,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_GREATER,              {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_4,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_RIGHT_BRACKET,        {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  PARAMETERS_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  PARAM_LIST_REST_2,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   ARGUMENTS_2,   SYNTAX_ERROR,  ARG_2,         SYNTAX_ERROR}},
    {T_HASH_INT_LITERAL,          {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_3,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  LITERAL_1}},
	{T_HASH_INT_OR_NULL,          {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_2,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_NULL_LITERAL,         {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_3,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  LITERAL_4}},
	{T_HASH_STRING_LITERAL,       {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  RETURN_REST_1,  EXPR,          REL_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  ADD_EXPR,      SYNTAX_ERROR,     SYNTAX_ERROR,  MULTI_EXPR,    SYNTAX_ERROR,       SYNTAX_ERROR,  TERM_3,        SYNTAX_ERROR,  ARGUMENTS_1,   ARG_LIST,      SYNTAX_ERROR,  LITERAL_3}},
	{T_HASH_STRING_OR_NULL,       {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       RETURN_TYPE_1,  DATA_TYPE_6,   SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_LESS_OR_EQUAL,        {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  REL_EXPR_REST_1,  REL_OP_5,      SYNTAX_ERROR,  ADD_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_LEFT_CURLY_BRACKET,   {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  STATEMENT_LIST_2,  SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_RIGHT_CURLY_BRACKET,  {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  NULL_COND_2,   SEQUENCE,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
	{T_HASH_MULTIPLICATION,       {SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,    SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,       SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,      SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,     SYNTAX_ERROR,  SYNTAX_ERROR,  MULTI_EXPR_REST_1,  MULTI_OP_1,    SYNTAX_ERROR,  TERM_REST_2,   SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR,  SYNTAX_ERROR}},
};

/**
 * @brief Vypočítá hash pro klíč do LL tabulky.
 */
size_t LLtable_hashFunction(char *key) {
    size_t hash = HASH_SEED;
    for(char *i = key; *i; i++) {
        hash = ((hash << 5) + hash) + (unsigned char)(*i);
    }
    return hash;
} // LLtable_hashFunction()

/**
 * @brief Najde pravidlo v LL tabulce na základě neterminálu a řetězce.
 */
int LLtable_findRule(int nt, char *str) {
    // Získání hash hodnoty pro vyhledávaný řetězec
    size_t hash = LLtable_hashFunction(str);

    // Nastavení indexů pro binární vyhledávání
    int left = 0;
    int right = TERMINAL_COUNT - 1;
    int mid;

    // Binární vyhledávání
    while(left <= right) {
        mid = (left + right) / 2;

        // Pokud najdeme odpovídající hash, vrátíme hodnotu pravidla pro daný neterminál
        if(table[mid].key == hash) {
            // Pokud pravidlo neexistuje, došlo k syntaktické chybě
            if(table[mid].value[nt] == SYNTAX_ERROR) {
                error_handle(ERROR_SYNTAX);
            }
            // Jinak pravidlo existuje a vrátímě ho
            else {
                return table[mid].value[nt];
            }
        }

        if(table[mid].key < hash) {
            // Hledaný hash je vyšší, posouváme levý index doprava
            left = mid + 1;
        }
        else {
             // Hledaný hash je nižší, posouváme pravý index doleva
            right = mid - 1;
        }
    }

    // Vrací interní chybový kód, pokud terminál není nalezen v tabulce
    error_handle(ERROR_INTERNAL);
    return ERROR_INTERNAL;
} // LLtable_findRule()

/*** Konec souboru lltable.c ***/
